spring.application.name=backend
spring.config.import=optional:file:./.env[.properties]
app.env.validation.enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5439/backend-4}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:backend}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:backend}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

logging.level.com.zaxxer.hikari=DEBUG

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY:}
spring.ai.openai.embedding.options.model=${SPRING_AI_OPENAI_EMBEDDING_OPTIONS_MODEL:text-embedding-3-small}
spring.ai.vectorstore.pgvector.initialize-schema=${SPRING_AI_VECTORSTORE_PGVECTOR_INITIALIZE_SCHEMA:true}
spring.ai.vectorstore.pgvector.dimensions=${SPRING_AI_VECTORSTORE_PGVECTOR_DIMENSIONS:1536}

spring.cloud.aws.endpoint=${SPRING_CLOUD_AWS_ENDPOINT:http://localhost:4666}
spring.cloud.aws.region.static=${SPRING_CLOUD_AWS_REGION_STATIC:us-east-1}
spring.cloud.aws.credentials.access-key=${SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY:test}
spring.cloud.aws.credentials.secret-key=${SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY:test}
